sonar.projectKey=cmd-rpg
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=**/*_tests.erl
sonar.exclusions=**/mutants/**,**/reports/**
sonar.erlang.eunit.reportsfolder=.marestail
sonar.erlang.eunit.coverdata.filename=eunit.coverdata
sonar.sourceEncoding=UTF-8
